WARNING  | 2023-04-19 13:05:02,524 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for sub_ea6c (1/2)
WARNING  | 2023-04-19 13:05:02,531 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

WARNING  | 2023-04-19 13:05:02,538 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for sub_ea6c (2/2)
WARNING  | 2023-04-19 13:05:02,539 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 52, in get_clinic
    clinic = self._proj.analyses.Clinic(func,
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

WARNING  | 2023-04-19 13:05:19,444 | Yasat.analyses.backward_slicing.engine_ail | Unusual expression Mull: (0x55e63b89<32> Mull Load(addr=stack_base-36, size=4, endness=Iend_LE))
WARNING  | 2023-04-19 13:05:19,445 | Yasat.analyses.backward_slicing.engine_ail | Unusual expression Mull: (0x55e63b89<32> Mull Load(addr=stack_base-36, size=4, endness=Iend_LE))
WARNING  | 2023-04-19 13:05:19,888 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for lcp_close (1/2)
WARNING  | 2023-04-19 13:05:19,891 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

WARNING  | 2023-04-19 13:05:19,899 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for lcp_close (2/2)
WARNING  | 2023-04-19 13:05:19,899 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 52, in get_clinic
    clinic = self._proj.analyses.Clinic(func,
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

WARNING  | 2023-04-19 13:05:23,385 | Yasat.analyses.backward_slicing.engine_ail | Unusual expression Mull: (0xc22e4507<32> Mulls r0<4>)
WARNING  | 2023-04-19 13:05:23,666 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for sub_40434c (1/2)
WARNING  | 2023-04-19 13:05:23,668 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

WARNING  | 2023-04-19 13:05:23,674 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for sub_40434c (2/2)
WARNING  | 2023-04-19 13:05:23,675 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 52, in get_clinic
    clinic = self._proj.analyses.Clinic(func,
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

WARNING  | 2023-04-19 13:05:26,306 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for sub_ea6c (1/2)
WARNING  | 2023-04-19 13:05:26,307 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

WARNING  | 2023-04-19 13:05:26,310 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for sub_ea6c (2/2)
WARNING  | 2023-04-19 13:05:26,311 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 52, in get_clinic
    clinic = self._proj.analyses.Clinic(func,
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 163, in _analyze
    self._recover_calling_conventions()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 432, in _recover_calling_conventions
    cc = self.project.analyses.CallingConvention(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 143, in __init__
    self._analyze_callsite_only()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 231, in _analyze_callsite_only
    self._analyze_callsite(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 379, in _analyze_callsite
    fact = self._collect_callsite_fact(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 500, in _collect_callsite_fact
    self._analyze_callsite_arguments(cc, caller_block_addr, call_insn_addr, rda, fact)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/calling_convention.py", line 548, in _analyze_callsite_arguments
    state = rda.observed_results[("insn", call_insn_addr, OP_BEFORE)]
KeyError: ('insn', 0, <ObservationPointType.OP_BEFORE: 0>)

WARNING  | 2023-04-19 13:05:39,828 | Yasat.knowledge_plugins.clinic_manager | Failed to build AIL graph for sub_410d84 (1/2)
WARNING  | 2023-04-19 13:05:39,833 | Yasat.knowledge_plugins.clinic_manager | Traceback (most recent call last):
  File "/home/bluesadi/dev/Yasat/Yasat/knowledge_plugins/clinic_manager.py", line 43, in get_clinic
    clinic = self._proj.analyses.Clinic(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 108, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 255, in _analyze
    _, stackarg_offsets = self._make_callsites(ail_graph, stack_pointer_tracker=spt)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/utils/timing.py", line 36, in timed_func
    return func(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 864, in _make_callsites
    AILGraphWalker(ail_graph, _handler, replace_nodes=True).walk()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/ailgraph_walker.py", line 21, in walk
    r = self.handler(node)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 843, in _handler
    csm = self.project.analyses.AILCallSiteMaker(
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 143, in __call__
    r = w(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/callsite_maker.py", line 40, in __init__
    self._analyze()
  File "/home/bluesadi/envs/Yasat/lib/python3.10/site-packages/angr/analyses/decompiler/callsite_maker.py", line 122, in _analyze
    raise NotImplementedError("Not implemented yet.")
NotImplementedError: Not implemented yet.

